version: '3.7'
services:
    # app:
    #     build: .
    #     tty: true
    #     volumes:
    #         - .:/app
    #     ports:
    #         - 5000:5000
    #     depends_on:
    #         - db
    db:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: okarin
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db
            - ./configdb:/data/configdb
